package:
  name: jq
  version: 0.0.1

source:
  git_rev: 
  git_url: https://github.com/gcomoretto/jq

requirements:
  host:
    - python
    - setuptools
    - requests

  run:
    - python

test:
  imports:
    - pytest
    - pytest-flake8
    - responses
    - pytest-runner
    - setuptools_scm

about:
  home: https://github.com/gcomoretto/jq
  license: MIT
  license_file: LICENSE
