package:
  name: jq
  version: 0.0.1

source:
  path: ..

build:
  entry_points:
    - testspecgen = jq.cli.testspecgen:main

requirements:
  build:
    - python

  run:
    - python
    - requests
    - arrow
    - beautifulsoup4
    - Jinja2
    - MarkupSafe    
    - pyandoc

about:
  home: https://github.com/gcomoretto/jq
  license: MIT
  license_file: LICENSE
  summary: Jira Query Project
