package:
  name: jq
  version: 0.0.1

source:
  git_rev:
  git_url: https://github.com/gcomoretto/jq

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home:
  license:
  license_file:
