package:
  name: jq
  version: "0.0.1"

source:
  git_rev: 
  git_url: https://github.com/gcomoretto/jq

requirements:
  host:
    - python
    - requests
    - arrow
    - beautifulsoup4
    - Jinja2
    - MarkupSafe    
    - pyandoc

  run:
    - python

about:
  home: https://github.com/gcomoretto/jq
  license: MIT
  license_file: LICENSE
  summary: Jira Query Project
